/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan3;

/**
 *
 * @author Dyah Ayu Shafitri
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bilangan1 = new javax.swing.JTextField();
        bilangan2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dikali = new javax.swing.JButton();
        dibagi = new javax.swing.JButton();
        ditambah = new javax.swing.JButton();
        dikurangi = new javax.swing.JButton();
        Hasil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Bilangan 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 59, 70, 14);

        jLabel2.setText("Bilangan 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 120, 80, 14);
        getContentPane().add(bilangan1);
        bilangan1.setBounds(169, 56, 100, 30);
        getContentPane().add(bilangan2);
        bilangan2.setBounds(169, 107, 100, 30);

        jLabel3.setText("Kalkulator Sederhana");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(131, 11, 160, 14);

        dikali.setText("X");
        dikali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dikaliActionPerformed(evt);
            }
        });
        getContentPane().add(dikali);
        dikali.setBounds(45, 164, 50, 40);

        dibagi.setText(":");
        dibagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibagiActionPerformed(evt);
            }
        });
        getContentPane().add(dibagi);
        dibagi.setBounds(128, 164, 50, 40);

        ditambah.setText("+");
        ditambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ditambahActionPerformed(evt);
            }
        });
        getContentPane().add(ditambah);
        ditambah.setBounds(211, 164, 50, 40);

        dikurangi.setText("-");
        dikurangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dikurangiActionPerformed(evt);
            }
        });
        getContentPane().add(dikurangi);
        dikurangi.setBounds(294, 164, 50, 40);

        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });
        getContentPane().add(Hasil);
        Hasil.setBounds(142, 247, 70, 40);

        jLabel4.setText("Hasil");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 220, 50, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dibagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibagiActionPerformed
       double bil1 = Double.parseDouble(bilangan1.getText());
       double bil2 = Double.parseDouble(bilangan2.getText());
       double hasil2 = bil1/bil2;
       Hasil.setText(String.valueOf(hasil2));
    }//GEN-LAST:event_dibagiActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilActionPerformed

    private void dikaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dikaliActionPerformed
       int bil1 = Integer.parseInt(bilangan1.getText());
       int bil2 = Integer.parseInt(bilangan2.getText());
       int hasil2 = bil1*bil2;
       Hasil.setText(String.valueOf(hasil2));
    }//GEN-LAST:event_dikaliActionPerformed

    private void ditambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ditambahActionPerformed
       int bil1 = Integer.parseInt(bilangan1.getText());
       int bil2 = Integer.parseInt(bilangan2.getText());
       int hasil2 = bil1+bil2;
       Hasil.setText(String.valueOf(hasil2));
    }//GEN-LAST:event_ditambahActionPerformed

    private void dikurangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dikurangiActionPerformed
       int bil1 = Integer.parseInt(bilangan1.getText());
       int bil2 = Integer.parseInt(bilangan2.getText());
       int hasil2 = bil1-bil2;
       Hasil.setText(String.valueOf(hasil2));
    }//GEN-LAST:event_dikurangiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField bilangan1;
    private javax.swing.JTextField bilangan2;
    private javax.swing.JButton dibagi;
    private javax.swing.JButton dikali;
    private javax.swing.JButton dikurangi;
    private javax.swing.JButton ditambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
